import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import readline from 'node:readline';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const proxyPath = path.join(repoRoot, 'src', 'proxy.js');
const echoServerPath = path.join(repoRoot, 'examples', 'echo-server.js');

test('proxy enforces policy end to end (allow, deny, env brokering, audit)', { timeout: 20000 }, async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'mcp-fw-test-'));
  const dataFile = path.join(dir, 'note.txt');
  fs.writeFileSync(dataFile, 'integration test contents');
  const auditPath = path.join(dir, 'audit.log');
  const policyPath = path.join(dir, 'policy.json');
  fs.writeFileSync(
    policyPath,
    JSON.stringify({
      server: { command: process.execPath, args: [echoServerPath] },
      tools: { allow: ['read_file', 'echo', 'print_env'] },
      filesystem: { allowedRoots: [dir] },
      network: { allowedDomains: [] },
      env: { allow: ['PATH', 'DEMO_VISIBLE'] },
      redactArgKeys: ['api_key'],
      jev: { enabled: false },
      auditLog: auditPath,
    }),
  );

  const proxy = spawn(process.execPath, [proxyPath, '--policy', policyPath], {
    cwd: repoRoot,
    env: { ...process.env, DEMO_VISIBLE: 'yes', TOP_SECRET_LEAK_TEST: 'no' },
    stdio: ['pipe', 'pipe', 'pipe'],
  });
  let proxyStderr = '';
  proxy.stderr.on('data', (d) => {
    proxyStderr += d;
  });

  let nextId = 1;
  const waiters = new Map();
  const rl = readline.createInterface({ input: proxy.stdout, crlfDelay: Infinity });
  rl.on('line', (line) => {
    let msg;
    try {
      msg = JSON.parse(line);
    } catch {
      return;
    }
    const w = waiters.get(msg.id);
    if (w) {
      waiters.delete(msg.id);
      w(msg);
    }
  });
  const call = (method, params) =>
    new Promise((resolve, reject) => {
      const id = nextId++;
      const timer = setTimeout(
        () => reject(new Error(`timeout on ${method}; proxy stderr: ${proxyStderr}`)),
        8000,
      );
      waiters.set(id, (msg) => {
        clearTimeout(timer);
        resolve(msg);
      });
      proxy.stdin.write(JSON.stringify({ jsonrpc: '2.0', id, method, params }) + '\n');
    });

  try {
    const init = await call('initialize', {
      protocolVersion: '2024-11-05',
      capabilities: {},
      clientInfo: { name: 'test-client', version: '0.0.0' },
    });
    assert.equal(init.result.serverInfo.name, 'echo-server');

    // Allowed: read inside the allowlisted root.
    const ok = await call('tools/call', { name: 'read_file', arguments: { path: dataFile } });
    assert.match(ok.result.content[0].text, /integration test contents/);

    // Denied: /etc/passwd is outside the roots, and the denial is a
    // JSON-RPC error generated by the firewall (the upstream never sees it).
    const denied = await call('tools/call', {
      name: 'read_file',
      arguments: { path: '/etc/passwd' },
    });
    assert.ok(denied.error, 'expected a JSON-RPC error for the denied read');
    assert.match(denied.error.message, /Blocked by mcp-server-firewall policy/);

    // Denied: tool not in the allowlist.
    const badTool = await call('tools/call', {
      name: 'delete_file',
      arguments: { path: dataFile },
    });
    assert.ok(badTool.error, 'expected a JSON-RPC error for the non-allowlisted tool');
    assert.ok(fs.existsSync(dataFile), 'denied delete must not have removed the file');

    // Env brokering: upstream sees DEMO_VISIBLE but not the secret.
    const envRes = await call('tools/call', { name: 'print_env', arguments: {} });
    const keys = JSON.parse(envRes.result.content[0].text);
    assert.ok(keys.includes('DEMO_VISIBLE'), 'allowlisted var should reach upstream');
    assert.ok(!keys.includes('TOP_SECRET_LEAK_TEST'), 'non-allowlisted var must not leak');
  } finally {
    proxy.stdin.end();
    proxy.kill();
  }

  // Audit log: requests and responses recorded with decisions.
  await new Promise((r) => setTimeout(r, 200));
  const entries = fs
    .readFileSync(auditPath, 'utf8')
    .trim()
    .split('\n')
    .map((l) => JSON.parse(l));
  assert.ok(
    entries.some((e) => e.direction === 'request' && e.decision === 'allow' && e.tool === 'read_file'),
    'audit log should contain the allowed read_file request',
  );
  assert.ok(
    entries.some((e) => e.direction === 'request' && e.decision === 'deny'),
    'audit log should contain at least one denied request',
  );
  assert.ok(
    entries.some((e) => e.direction === 'response' && e.ok === true),
    'audit log should contain upstream responses',
  );
  assert.ok(
    entries.every((e) => typeof e.ts === 'string' && typeof e.reason === 'string' || e.direction === 'response'),
    'audit entries should be structured records',
  );

  fs.rmSync(dir, { recursive: true, force: true });
});
